---
title: "🏀 March Madness Dashboard 2024 🏀"
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "white"
      fg: "black" 
      primary: "#065cb5"
      navbar-bg: "black"
      base_font: 
        google: Passion One
      heading_font:
        google: Passion One
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: Satisfy
          local: false
    orientation: rows
    vertical_layout: fill
---

<style>
.navbar-brand {
  font-size: 28px;
}
.chart-title {  /* chart_title  */
   font-size: 28px;
</style>

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(png)
library(showtext) # for custom Google fonts
library(wordcloud2) 
library(tidytext)
library(reactablefmtr)
library(flexdashboard)
library(flextable)
library(plotly)
library(downloadthis)

set.seed(1994)

# Plotting parameters
fontFamily <- "Passion One" # update base_font and heading_font in the YAML as well
textSize <- 20
color_gradient <- c("#ffa241", "white", "#065cb5")

# Downloading Google fonts for plots
font_add_google(name = str_to_title(fontFamily), 
                family = fontFamily)
```

```{r, include = FALSE, eval = TRUE}
# Logo and home location information from: https://www.google.com/maps/d/u/0/viewer?mid=1JaZgEuzxZ5Sn2UjtA1vTIstU8Fjfl8MM&ll=39.374932225470644%2C-95.83631723748385&z=5

# Setting working directory
if(Sys.info()["sysname"] != "Darwin") {
start_dir <- "H:/My Drive/dilerand@mail.gvsu.edu 2022-11-21 21 19/Other/Fun/March Madness/"
} else {
  start_dir <- "/Users/dilerand/Library/CloudStorage/GoogleDrive-asdilernia@gmail.com/My Drive/dilerand@mail.gvsu.edu 2022-11-21 21:19/Other/Fun/March Madness/"
}

showtext_auto()

womens <- FALSE
tourney_year <- 2024

# Setting working directory
setwd(paste0(start_dir, tourney_year))

# Setting file paths
stageDir <- paste0("march-machine-learning-mania-", tourney_year, "/")

setwd(paste0(start_dir, tourney_year))

# Importing team spellings to add in team IDs
team_spellings <- map_dfr(.x = womens,
                 .f = function(women) {read_csv(paste0("march-machine-learning-mania-2024/", 
                                            ifelse(women, "W", "M"),
                                            "TeamSpellings.csv"))}) |> 
  dplyr::mutate(merge_team = str_remove_all(str_to_lower(TeamNameSpelling), pattern = " "))

team_spellings <- team_spellings |> 
  bind_rows(dplyr::mutate(team_spellings, merge_team = str_remove_all(merge_team, pattern = "[^[:alnum:]]")))

# Importing cleaned logos
team_logos <- tibble(team = str_remove_all(list.files("../team_logo_images",  full.names = FALSE),
                                           pattern = stringr::fixed(".png")),
                     path = list.files("../team_logo_images",  full.names = TRUE)) |> 
  dplyr::rename(merge_team = team) |> 
  left_join(team_spellings, by = c("merge_team" = "merge_team")) |> 
  left_join(team_spellings, 
            by = c("TeamID" = "TeamID"),
            suffix = c("_drop", ""),
            relationship = "many-to-many") |> 
  dplyr::select(-ends_with("drop"), -TeamNameSpelling) |> 
  dplyr::distinct()
```

```{r, include = FALSE, eval = TRUE, warning = FALSE}
# This person did it with ggplot: https://stackoverflow.com/questions/16290052/march-madness-brackets-with-ggplot2

# Function for creating bracket
draw_bracket <- function(submission, seeds, teams, logo = NULL, logo_info = team_logos, lineColor = "black", 
                        fontFamily = "Passion One", textSize = 6, regions = setNames(c("EAST", "WEST", "SOUTH", "MIDWEST"), c("W", "X", "Z", "Y")), retData = FALSE, ndigits = 1) {
  
    region_names <- names(regions)
    
    showtext_auto()
    
  # Downloading Google fonts for plots
  font_add_google(name = str_to_title(fontFamily), 
                family = fontFamily)
  
  ### Helper functions
  first_evens <- function(x) {seq(from = 2, to = 2*x, length.out = x)}
  first_odds <- function(x) {seq(from = 1, to = 2*x-1, length.out = x)}
  
  ### calculate y-values for horizontal lines:
  ### this is for top-left corner of the bracket,
  ### but multiplying sequences by -1 makes these 
  ### values work for bottom right and left corners;
  ### final round has teams at y=2*off.set
  
  r1.y.width <- 1.5*strheight(s="Virginia Common",units="in") # this effects the width of the first round
  r1.y.offset <- 0.125*r1.y.width # this effects distance from y=0
  
  r1.y <- seq(from=r1.y.offset,to=r1.y.offset+r1.y.width,length.out=16)
  r2.y <- seq(from=mean(r1.y[1:2]),to=mean(r1.y[15:16]),length.out=8)
  r3.y <- seq(from=mean(r2.y[1:2]),to=mean(r2.y[7:8]),length.out=4)
  r4.y <- seq(from=mean(r3.y[1:2]),to=mean(r3.y[3:4]),length.out=2)
  r5.y <- seq(from=mean(r4.y[1:2]),to=mean(r4.y[1:2]),length.out=1)
  r6.y <- 1.5*r1.y.offset
  
  ### calculate horizontal bar start and stop coordinates
  ### note that there are 6 total rounds -- 5 rounds per quadrant
  r1.x.width <- 1.25*strwidth("Viriginia Commonwealth","inches") # how long should horizontal lines be?
  r1.x.offset <- 1
  round.break.points <- -(seq(from=0,to=7*r1.x.width,by=r1.x.width)+r1.x.offset)
  
  r1.x <- round.break.points[7:6]
  r2.x <- round.break.points[6:5]
  r3.x <- round.break.points[5:4]
  r4.x <- round.break.points[4:3]
  r5.x <- round.break.points[3:2]
  r6.x <- round.break.points[2:1]
  
  ### calculate verticals line coordinates: these are based off of
  ### r1.y values. Round 5 verticals need to connect the four subtrees
  ### via the top-left <-> bottom-left and top-right <-> bottom-right
  
  r1.verticals.start <- r1.y[first_odds(8)]
  r1.verticals.stop <- r1.y[first_evens(8)]
  
  r2.verticals.start <- r2.y[first_odds(4)]
  r2.verticals.stop <- r2.y[first_evens(4)]
  
  r3.verticals.start <- r3.y[first_odds(2)]
  r3.verticals.stop <- r3.y[first_evens(2)]
  
  r4.verticals.start <- r4.y[first_odds(1)]
  r4.verticals.stop <- r4.y[first_evens(1)]
  
  r5.verticals.start <- r5.y[1]
  r5.verticals.stop <- -r5.y[1]
  
  empty.bracket <- ggplot() + 
    theme_bw() + 
    theme(axis.line = element_blank(), 
          axis.text = element_blank(), 
          axis.ticks = element_blank(), 
          axis.title = element_blank(), 
          panel.border = element_blank(),
          panel.grid = element_blank(),
          plot.margin = unit(c(0, 0, -6, -6), "mm"),
          text = element_text(size = 12, hjust = 0, vjust = 0)) + 
    coord_cartesian(ylim = c(-1.05*r1.y[16],1.05*r1.y[16]), 
                    xlim = c(1.025*r1.x[1],-1.025*r1.x[1]))
  
  vec1x <- c(1, 1, -1, -1)
  vec1y <- c(1, -1, 1, -1)
  vec11 <- c(1, -1)
  
  lineCoords <- list()
  
  lineCoords$R1 <- tibble(x = c(rep(as.numeric(vec1x %o% r1.x[1]), each = 16),
                                rep(as.numeric(vec1x %o% r1.x[2]), each = 8)),
                          y = c(as.numeric(r1.y %o% vec1y), 
                                as.numeric(r1.verticals.start %o% vec1y)),
                          xend = c(rep(as.numeric(vec1x %o% r1.x[2]), each = 16),
                                   rep(as.numeric(vec1x %o% r1.x[2]), each = 8)),
                          yend = c(as.numeric(r1.y %o% vec1y),
                                   as.numeric(r1.verticals.stop %o% vec1y)),
                          Round = c(rep(1, times = 96)))
  
  lineCoords$R2 <- tibble(x = c(rep(as.numeric(vec1x %o% r2.x[1]), each = 8),
                                rep(as.numeric(vec1x %o% r2.x[2]), each = 4)),
                          y = c(as.numeric(r2.y %o% vec1y), 
                                as.numeric(r2.verticals.start %o% vec1y)),
                          xend = c(rep(as.numeric(vec1x %o% r2.x[2]), each = 8),
                                   rep(as.numeric(vec1x %o% r2.x[2]), each = 4)),
                          yend = c(as.numeric(r2.y %o% vec1y),
                                   as.numeric(r2.verticals.stop %o% vec1y)),
                          Round = c(rep(2, times = 48)))
  
  lineCoords$R3 <- tibble(x = c(rep(as.numeric(vec1x %o% r3.x[1]), each = 4),
                                rep(as.numeric(vec1x %o% r3.x[2]), each = 2)),
                          y = c(as.numeric(r3.y %o% vec1y), 
                                as.numeric(r3.verticals.start %o% vec1y)),
                          xend = c(rep(as.numeric(vec1x %o% r3.x[2]), each = 4),
                                   rep(as.numeric(vec1x %o% r3.x[2]), each = 2)),
                          yend = c(as.numeric(r3.y %o% vec1y),
                                   as.numeric(r3.verticals.stop %o% vec1y)),
                          Round = c(rep(3, times = 24)))
  
  lineCoords$R4 <- tibble(x = c(rep(as.numeric(vec1x %o% r4.x[1]), each = 2),
                                rep(as.numeric(vec1x %o% r4.x[2]), each = 1)),
                          y = c(as.numeric(r4.y %o% vec1y), 
                                as.numeric(r4.verticals.start %o% vec1y)),
                          xend = c(rep(as.numeric(vec1x %o% r4.x[2]), each = 2),
                                   rep(as.numeric(vec1x %o% r4.x[2]), each = 1)),
                          yend = c(as.numeric(r4.y %o% vec1y),
                                   as.numeric(r4.verticals.stop %o% vec1y)),
                          Round = c(rep(4, times = 12)))
  
  lineCoords$R5 <- tibble(x = r5.x[rep(c(1, 1, 2), 2)]*rep(vec11, each = 3),
                          y = r5.y*rep(c(1, -1, -1), times = 2),
                          xend = r5.x[2]*rep(vec11, each = 3),
                          yend = r5.y*rep(c(1, -1, 1), times = 2),
                          Round = c(rep(5, times = 6)))
  
  lineCoords$R6 <- tibble(x = r6.x*vec11, 
                          y = r6.y*vec11, 
                          xend = rev(r6.x)*vec11, 
                          yend = r6.y*vec11,
                          Round = c(rep(6, times = 2)))
  
  lineCoords$R7 <- tibble(x = mean(r6.x),
                          y = 0,
                          xend = -mean(r6.x),
                          yend = 0,
                          Round = 7)
  
  lineCoords$R0 <- tibble(x = rep(c(r4.x[1], -(2*r4.x[2]-r4.x[1])), each = 2),
                          y = -r1.y[16]*vec1y,
                          xend = rep(c(2*r4.x[2]-r4.x[1], -r4.x[1]), each = 2),
                          yend = -r1.y[16]*vec1y,
                          Round = rep(0, 4))
  
  fullCoords <- bind_rows(lineCoords) |> 
    dplyr::mutate(Region = case_when(y < 0 & Round == 5 & x == xend ~ "Final",
                                     x < 0 & y > 0 & Round < 6 ~ regions[1],
                                     x < 0 & y < 0 & Round < 6 ~ regions[2],
                                     x > 0 & y > 0 & Round < 6 ~ regions[3],
                                     x > 0 & y < 0 & Round < 6 ~ regions[4],
                                     TRUE ~ "Final"))
  
  # Coordinates for drawing team names & probabilities
    name_coords <- fullCoords |> 
    dplyr::filter(x != xend) |> 
    dplyr::mutate(Xstart = x, 
                  Y = y) |> 
    dplyr::select(Round, Region, Xstart, Y) |> 
      dplyr::group_by(Round, Region) |> 
      dplyr::arrange(desc(Y)) |> 
      dplyr::mutate(Matchup = rep(1:(n() / 2), each = 2)[1:n()],
                    round_team = case_when(Round == 5 & Region %in% regions[c(1, 3)] ~ 1,
                                           Round == 5 & Region %in% regions[c(2, 4)] ~ 2,
                                           Round == 6 & Region %in% regions[c(1, 2)] ~ 1,
                                           Round == 6 & Region %in% regions[c(3, 4)] ~ 2,
                                           TRUE ~ 1:n()
                    )) |> 
      dplyr::ungroup()
  
  # Printing bracket with lines
  empty.bracket <- empty.bracket + 
    geom_segment(data = fullCoords, 
                 color = lineColor, 
                 mapping = aes(x = x, xend = xend, y = y, yend = yend))
  
  if(!is.null(logo)) {
  # Add NCAA logo
  empty.bracket <- empty.bracket + 
    annotation_raster(logo, xmin = mean(r6.x), xmax = -mean(r6.x),
                      ymin = r1.y[13]*1.05, ymax = r1.y[16]*1.05)
  }
  
  # Cleaning up predictions
  preds <- submission |> 
    mutate(Team1 = as.integer(map_chr(str_split(ID, pattern = "_"), 2)), 
           Team2 = as.integer(map_chr(str_split(ID, pattern = "_"), 3))) |> 
    dplyr::select(Team1, Team2, pred)
  
  # Data for drawing bracket
  bracketData <- preds |> 
    right_join(seeds, by = c("Team1" = "TeamID")) |> 
    dplyr::rename(Seed1 = Seed, Pred1 = pred) |> 
    right_join(seeds, by = c("Team2" = "TeamID", "Season" = "Season")) |> 
    dplyr::rename(Seed2 = Seed) |> 
    mutate(Pred2 = 1 - Pred1) |> 
    dplyr::select(Season, Team1:Pred1, Pred2, Seed1, Seed2) |> 
    mutate(Region1 = str_sub(Seed1, start = 1, end = 1),
           Region2 = str_sub(Seed2, start = 1, end = 1),
           PlayIn = case_when(str_detect(Seed1, pattern = "a|b") &
                                str_detect(Seed2, pattern = "a|b") &
                                Region1 == Region2 & 
                                str_remove(Seed1, pattern = "a|b") == str_remove(Seed2, pattern = "a|b")~ TRUE,
                              TRUE ~ FALSE),
           Seed1 = as.integer(str_sub(str_remove(Seed1, pattern = "a|b"), start = 2, end = -1)),
           Seed2 = as.integer(str_sub(str_remove(Seed2, pattern = "a|b"), start = 2, end = -1))) |> 
    mutate(Region1 = case_when(Region1 == region_names[2] ~ regions[2],
                               Region1 == region_names[1] ~ regions[1],
                               Region1 == region_names[3] ~ regions[3],
                               Region1 == region_names[4] ~ regions[4]),
           Region2 = case_when(Region2 == region_names[2] ~ regions[2],
                               Region2 == region_names[1] ~ regions[1],
                               Region2 == region_names[3] ~ regions[3],
                               Region2 == region_names[4] ~ regions[4])) |> 
    left_join(teams, by = c("Team1" = "TeamID")) |> 
    left_join(teams, by = c("Team2" = "TeamID"), suffix = c("1", "2"))
  
  bracketDataFull <- bracketData |> 
    bind_rows(bracketData |> 
                rename_with(~ gsub("1", "A", .x, fixed = TRUE), ends_with("1")) |> 
                rename_with(~ gsub("2", "B", .x, fixed = TRUE), ends_with("2")) |> 
                rename_with(~ gsub("A", "2", .x, fixed = TRUE), ends_with("A")) |> 
                rename_with(~ gsub("B", "1", .x, fixed = TRUE), ends_with("B")) |> 
                dplyr::select(colnames(bracketData)))
  
  # First four play-in games
  firstFour <- bracketDataFull |> 
    dplyr::filter(PlayIn) |> 
    dplyr::mutate(Round = 0, 
                  Matchup = as.integer(factor(paste0(ifelse(Team1 < Team2, paste0(Team1, "_", Team2), 
                                                                       paste0(Team2, "_", Team1)))))) |> 
    dplyr::select(Seed1, Seed2, Region1, Region2, Round, Matchup)
  
  # Possible matchups
  round1 <- data.frame(Seed1 = 1:8, Seed2 = 16:9, 
                       Region1 = rep(c(regions[2], regions[4], regions[3], regions[1]), each = 8)) |> 
    dplyr::mutate(Region2 = Region1, Round = 1,
                  Matchup = case_when(Seed1 == 1 ~ 1,
                                      Seed1 == 8 ~ 2,
                                      Seed1 == 5 ~ 3,
                                      Seed1 == 4 ~ 4,
                                      Seed1 == 6 ~ 5,
                                      Seed1 == 3 ~ 6,
                                      Seed1 == 7 ~ 7,
                                      Seed1 == 2 ~ 8))
  
  round2 <- map_dfr(.x = rep(list(list(c(1, 16), c(8, 9)), list(c(5, 12), c(4, 13)), 
                                  list(c(6, 11), c(3, 14)), list(c(7, 10), c(2, 15))), 4), 
                    .f = function(x) {expand_grid(Seed1 = x[[1]], Seed2 = x[[2]])}) |>  
    mutate(Region1 = rep(c(regions[2], regions[4], regions[3], regions[1]), each = 16)) |> 
    mutate(Region2 = Region1, Round = 2,
           Matchup = case_when(Seed1 %in% c(1, 16) ~ 1,
                               Seed1 %in% c(5, 12) ~ 2,
                               Seed1 %in% c(6, 11) ~ 3,
                               Seed1 %in% c(7, 10) ~ 4))
  
  round3 <- expand_grid(Seed1 = c(1, 16, 8, 9), Seed2 = c(5, 12, 4, 13), 
                        Region1 = c(regions[2], regions[4], regions[3], regions[1])) |>
    bind_rows(expand_grid(Seed1 = c(6, 11, 3, 14), Seed2 = c(7, 10, 2, 15), 
                          Region1 = c(regions[2], regions[4], regions[3], regions[1]))) |> 
    dplyr::mutate(Region2 = Region1, Round = 3, Matchup = rep(1:2, each = 64))
  
  round4 <- expand_grid(Seed1 = c(1, 16, 8, 9, 5, 12, 4, 13), 
                        Seed2 = c(6, 11, 3, 14, 7, 10, 2, 15), 
                        Region1 = c(regions[2], regions[4], regions[3], regions[1])) |> 
    dplyr::mutate(Region2 = Region1, Round = 4, Matchup = 1)
  
  round5 <- expand_grid(Seed1 = 1:16, Seed2 = 1:16, 
                        Region1 = c(regions[1], regions[3])) |> 
    dplyr::mutate(Region2 = ifelse(Region1 == regions[1], regions[2], regions[4]), Round = 5, 
                  Matchup = 1)
  
  round6 <- expand_grid(Seed1 = 1:16, Seed2 = 1:16, 
                        Region1 = c(regions[1], regions[2]),
                        Region2 = c(regions[3], regions[4])) |> 
    dplyr::mutate(Round = 6, Matchup = 1)
  
  roundsWide <- bind_rows(firstFour, round1, round2, round3, 
                          round4, round5, round6) |> 
    left_join(bracketDataFull |> 
                dplyr::select(-Season, -Team1, -Team2),
              relationship = "many-to-many")
  
  roundsLong <- roundsWide |> 
    pivot_longer(cols = c(Seed1, Seed2), 
                 names_to = "Team", values_to = "Seed") |> 
    arrange(Round, Region1, Matchup, Team, Seed) |> 
    dplyr::mutate(Pred1 = sprintf(paste0("%.", ndigits, "f%%"), 100 * Pred1), 
                  Pred2 = sprintf(paste0("%.", ndigits, "f%%"), 100 * Pred2),
                  Winner = ifelse(Pred1 > Pred2, TeamName1, TeamName2), 
                  TeamName = case_when(
                  Team == "Seed1" & PlayIn ~ paste0(paste0(" (", Pred1, ") ", TeamName1, " ", Seed),
                                                      " vs. ", paste0(Seed, " ", TeamName2, " (", Pred2, ") ")),
                  Team == "Seed2" & PlayIn ~ paste0(paste0("(", Pred2, ") ", TeamName2, " ", Seed),
                                                      " vs. ", paste0(Seed, " ", TeamName1, " (", Pred1, ")")),
                  Team == "Seed1" & Region1 %in% c(regions[4], regions[3]) ~ paste0(Seed, " ", TeamName1, " (", Pred1, ")"),
                  Team == "Seed2" & Region2 %in% c(regions[4], regions[3]) ~ paste0(Seed, " ", TeamName2, " (", Pred2, ")"),
                  Team == "Seed1" & Region1 %in% c(regions[1], regions[2]) ~ paste0("(", Pred1, ") ", TeamName1, " ", Seed),
                  Team == "Seed2" & Region2 %in% c(regions[1], regions[2]) ~ paste0("(", Pred2, ") ", TeamName2, " ", Seed)))
  
  # Printing first four play-in games
  r0Labs <- roundsLong |> 
    dplyr::filter(Round == 0) |> 
    dplyr::arrange(Matchup) |> 
    dplyr::group_by(Matchup) |> 
    dplyr::slice(1) |> 
    dplyr::ungroup() |> 
    dplyr::mutate(Xstart = c(r4.x[1], r4.x[1], 
                      -(2*r4.x[2]-r4.x[1]), 
                      -(2*r4.x[2]-r4.x[1])),
                  Y = c(r1.y[16], -r1.y[16], 
                        r1.y[16], -r1.y[16]))
  
  # Winners from first four play-in games
  r0Winners <- roundsLong |> 
    dplyr::filter(Round == 0) |> 
    dplyr::arrange(Matchup) |> 
    dplyr::group_by(Matchup) |> 
    dplyr::slice(1) |> 
    dplyr::ungroup() |> 
    pull(Winner) |> 
    unique()
  
  playins <- roundsLong |> 
    dplyr::filter(Round == 0) |> 
    dplyr::arrange(Matchup) |> 
    dplyr::group_by(Matchup) |> 
    dplyr::slice(1) |> 
    dplyr::ungroup() |> 
    dplyr::select(TeamName1:TeamName2) |> 
    unlist()
  
  r0Losers <- playins[which(!(playins %in% r0Winners))]
  
  # Printing round 1 teams
  r1Labs <- roundsLong |> 
    dplyr::filter(Round == 1, !(TeamName1 %in% r0Losers), 
                              !(TeamName2 %in% r0Losers)) |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup() |> 
    left_join(dplyr::rename(name_coords, Region1 = Region))
  
  # Winners from round 1
  r1Winners <- roundsLong |> 
    dplyr::filter(Round == 1, !(TeamName1 %in% r0Losers), 
                              !(TeamName2 %in% r0Losers)) |> 
    pull(Winner) |> 
    unique()
  
  # Printing round 2 teams
  r2Labs <- roundsLong |> 
    dplyr::filter(Round == 2, TeamName1 %in% r1Winners, 
                              TeamName2 %in% r1Winners) |> 
    dplyr::distinct() |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup() |> 
    left_join(dplyr::rename(name_coords, Region1 = Region))
  
  # Winners from round 2
  r2Winners <- roundsLong |> 
    dplyr::filter(Round == 2, TeamName1 %in% r1Winners, 
                              TeamName2 %in% r1Winners) |> 
    dplyr::distinct() |>
    dplyr::pull(Winner) |> 
    unique()
  
  # Printing round 3 teams
  r3Labs <- roundsLong |> 
    dplyr::filter(Round == 3, TeamName1 %in% r2Winners, 
                              TeamName2 %in% r2Winners) |> 
    dplyr::distinct() |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup() |> 
    left_join(dplyr::rename(name_coords, Region1 = Region))
  
  # Winners from round 3
  r3Winners <- roundsLong |> 
    dplyr::filter(Round == 3, TeamName1 %in% r2Winners, 
                              TeamName2 %in% r2Winners) |> 
    dplyr::distinct() |>
    dplyr::pull(Winner) |> 
    unique()
  
  # Printing round 4 teams
  r4Labs <- roundsLong |> 
    dplyr::filter(Round == 4, TeamName1 %in% r3Winners, 
                              TeamName2 %in% r3Winners) |> 
    dplyr::distinct() |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup() |> 
    left_join(dplyr::rename(name_coords, Region1 = Region))
  
  # Winners from round 4
  r4Winners <- roundsLong |> 
    dplyr::filter(Round == 4, TeamName1 %in% r3Winners, 
                              TeamName2 %in% r3Winners) |> 
    dplyr::distinct() |>
    pull(Winner) |> 
    unique()
  
  # Printing round 5 teams
  r5Labs <- roundsLong |> 
    dplyr::filter(Round == 5, TeamName1 %in% r4Winners, 
                              TeamName2 %in% r4Winners) |> 
    dplyr::distinct() |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup() |>  
    left_join(
  name_coords |> 
  dplyr::filter(Round == 5) |> 
    dplyr::mutate(Region1 = case_when(Region %in% regions[c(1, 2)] ~ regions[1],
                                      Region %in% regions[c(3, 4)] ~ regions[3],
                                      TRUE ~ NA),
                  Region2 = case_when(Region %in% regions[c(1, 2)] ~ regions[2],
                                      Region %in% regions[c(3, 4)] ~ regions[4],
                                      TRUE ~ NA))
    )
  
  # Winners from round 5
  r5Winners <- roundsLong |> 
    dplyr::filter(Round == 5, TeamName1 %in% r4Winners, 
                              TeamName2 %in% r4Winners) |> 
    dplyr::distinct() |>
    pull(Winner) |> 
    unique()
  
  # Printing round 6 teams
  r6Labs <- roundsLong |> 
    dplyr::filter(Round == 6, TeamName1 %in% r5Winners, 
                              TeamName2 %in% r5Winners) |> 
    dplyr::distinct() |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup() |>  
    left_join(
  name_coords |> 
  dplyr::filter(Round == 6) |> 
    dplyr::select(-Region)
    )
  
  # Winners from round 6 (grand overall winner)
  r6Winner <- roundsLong |> 
    dplyr::filter(Round == 6, TeamName1 %in% r5Winners, 
                              TeamName2 %in% r5Winners) |> 
    dplyr::distinct() |>
    pull(Winner) |> 
    unique()
  
  r7Labs <- dplyr::slice_head(r6Labs, n = 1) |> 
    dplyr::mutate(Region1 = "Championship", Region2 = "Championship", Round = 7,
                  Xstart = 0 - nchar(r6Winner) / 10, Y = 0, TeamName = r6Winner) |> 
    dplyr::group_by(Region1, Region2) |> 
    dplyr::mutate(round_team = 1:n()) |> 
    dplyr::ungroup()
  
  # Printing filled out bracket
  sizeParam <- 3
  labData <- bind_rows(r0Labs, r1Labs, r2Labs, r3Labs, 
                       r4Labs, r5Labs, r6Labs, r7Labs)
  
  # Adding team and regions names to bracket, 
  # and adding small space for text above lines
  v_adjust <- 0.005
  bracketGG <- empty.bracket + # Adding regions 1 and 2 games
    geom_text(data = dplyr::filter(dplyr::mutate(labData, Y = Y + v_adjust),
                                   Region1 %in% regions[c(1:2)],
                                   Round < 6, Round > 0),
              mapping = aes(x = Xstart, y = Y,
                               label = TeamName, text = TeamName),
              size = rel(textSize), hjust = 0, vjust = 0,
              family = fontFamily) + # Adding regions 3 and 4 games
        geom_text(data = dplyr::filter(dplyr::mutate(labData, Y = Y + v_adjust),
                                   Region1 %in% regions[c(3:4)],
                                   Round < 6, Round > 0),
              mapping = aes(x = Xstart, y = Y,
                               label = TeamName, text = TeamName),
              size = rel(textSize), hjust = 1, vjust = 0,
              family = fontFamily) + # Adding play-in games
            geom_text(data = dplyr::filter(dplyr::mutate(labData, Y = Y + v_adjust),
                                           Round == 0),
              mapping = aes(x = Xstart, y = Y,
                               label = TeamName, text = TeamName),
              size = rel(textSize), hjust = 0, vjust = 0,
              family = fontFamily) + # Adding championship game
                geom_text(data = dplyr::filter(dplyr::mutate(labData, Y = Y + v_adjust),
                                           Round == 6, Region1 %in% regions[1:2]),
              mapping = aes(x = Xstart, y = Y,
                               label = TeamName, text = TeamName),
              size = rel(textSize), hjust = 0, vjust = 0,
              family = fontFamily) + # Adding champion
                    geom_text(data = dplyr::filter(dplyr::mutate(labData, Y = Y + v_adjust),
                                           Round == 7),
              mapping = aes(x = 0, y = 0 + v_adjust,
                               label = TeamName, text = TeamName),
              size = rel(textSize), hjust = 0.5, vjust = 0,
              family = fontFamily) + # Add region labels for regions 1 & 2
    geom_text(data = tibble(Region = rev(regions[1:2]),
                                  Xstart = rep(unique(r4Labs$Xstart)[1], 2),
                                  Y = c(mean(unique(r4Labs$Y)[3:4]), 
                                        mean(unique(r4Labs$Y)[1:2]))),
                    aes(x = Xstart, y = Y,
                        label = Region, text = Region), nudge_y = 0, 
                    color = "#065cb5",
                    size = rel(textSize*1.5)) + # Add region labels for regions 3 & 4
        geom_text(data = tibble(Region = rev(regions[3:4]),
                                  Xstart = rep(unique(r4Labs$Xstart)[2], 2),
                                  Y = c(mean(unique(r4Labs$Y)[3:4]), 
                                        mean(unique(r4Labs$Y)[1:2]))),
                    aes(x = Xstart, y = Y,
                        label = Region, text = Region), nudge_y = 0, 
                    color = "#065cb5",
                    size = rel(textSize*1.5)) +
    theme(text = element_text(family = fontFamily,
                              size = rel(textSize)))
  
  # Creating data for reactable table
  ret <- bracketData |>
    dplyr::mutate(Pred1 = as.numeric(Pred1),
                  Pred2 = as.numeric(Pred2)) |> 
    dplyr::mutate(SeedFav = ifelse(Pred1 > Pred2, Seed1, Seed2),
                  Favorite = ifelse(Pred1 > Pred2, 
                                    TeamName1, TeamName2), 
                  SeedDog = ifelse(Pred1 < Pred2, Seed1, Seed2),
                  Underdog = ifelse(Pred1 < Pred2, 
                                    TeamName1, TeamName2),
                  `Favorite Win Probability` = as.numeric(ifelse(Pred1 > Pred2, Pred1, Pred2))) |> 
    dplyr::select(SeedFav, Favorite, SeedDog, Underdog, `Favorite Win Probability`)
  
  if(retData) {
    return(list(bracketGG = bracketGG, ret = ret))
  } else {
    return(bracketGG)
  }
  
  return(list(bracketGG = bracketGG, ret = ret))
}

# lineColor = "black"; fontFamily = "Passion One"; textSize = 6; retData = FALSE; seeds = mySeeds; submission = nnet_submission_M; teams = myTeams; textSize = 4; retData = TRUE; logo = myLogo; regions = setNames(c("South", "East", "Midwest", "West"), c("X", "W", "Y", "Z"))

# Function for simulating NCAA Tournament

# Inputs for drawing bracket
womens <- setNames(c(TRUE, FALSE), c("W", "M"))
seedsPaths <- map(.x = womens,
                 .f = function(x) {paste0(stageDir, ifelse(x, "W", "M"), "NCAATourneySeeds.csv")
                 })

mySeeds <- map(.x = seedsPaths,
                 .f = function(file_path) {
                   read_csv(paste0(file_path)) |> 
  dplyr::filter(Season == tourney_year)
                 })

teamsPaths <- map(.x = womens,
                 .f = function(x) {paste0(stageDir, ifelse(x, "W", "M"), "Teams.csv")})

myTeams <- map(.x = teamsPaths,
                 .f = function(x) {read_csv(x) |> 
  dplyr::select(TeamID:TeamName)})

myLogo <- png::readPNG("../2022/March_Madness_logo.png")

# Drawing bracket
lda_submissions <- map(.x = womens,
                 .f = function(x) {
                   readr::read_csv(paste0("Preds/preds_", ifelse(x, "W", "M"), "_Awin_lda.csv"))})

region_info <- list(M = setNames(c("EAST", "WEST", "SOUTH", "MIDWEST"), c("W", "X", "Z", "Y")),
                    W = setNames(c("ALBANY 1", "PORTLAND 4", "ALBANY 2", "PORTLAND 3"), c("W", "X", "Y", "Z")))

bracket_res_mens <- draw_bracket(submission = lda_submissions$M, 
            seeds = mySeeds$M, teams = myTeams$M, textSize = 3,
            retData = TRUE, regions = region_info$M)

bracket_res_womens <- draw_bracket(submission = lda_submissions$W, 
            seeds = mySeeds$W, teams = myTeams$W, textSize = 3,
            retData = TRUE, regions = region_info$W)
```

```{r}
# Function for making data set on all possible matchups
make_matchups_data <- function(submission, seeds, teams, 
                        regions = setNames(c("SOUTH", "EAST", "MIDWEST", "WEST"),
                        c("X", "W", "Y", "Z"))) {
  
    region_names <- names(regions)
  
  # Cleaning up predictions
  preds <- submission |> 
    mutate(Team1 = as.integer(map_chr(str_split(ID, pattern = "_"), 2)), 
           Team2 = as.integer(map_chr(str_split(ID, pattern = "_"), 3))) |> 
    dplyr::select(Team1, Team2, pred)
  
  # Data for drawing bracket
  bracketData <- preds |> 
    right_join(seeds, by = c("Team1" = "TeamID")) |> 
    dplyr::rename(Seed1 = Seed, Pred1 = pred) |> 
    right_join(seeds, by = c("Team2" = "TeamID", "Season" = "Season")) |> 
    dplyr::rename(Seed2 = Seed) |> 
    mutate(Pred2 = 1 - Pred1) |> 
    dplyr::select(Season, Team1:Pred1, Pred2, Seed1, Seed2) |> 
    mutate(Region1 = str_sub(Seed1, start = 1, end = 1),
           Region2 = str_sub(Seed2, start = 1, end = 1),
           PlayIn = case_when(str_detect(Seed1, pattern = "a|b") &
                                str_detect(Seed2, pattern = "a|b") &
                                Region1 == Region2 & 
                                str_remove(Seed1, pattern = "a|b") == str_remove(Seed2, pattern = "a|b")~ TRUE,
                              TRUE ~ FALSE),
           Seed1 = as.integer(str_sub(str_remove(Seed1, pattern = "a|b"), start = 2, end = -1)),
           Seed2 = as.integer(str_sub(str_remove(Seed2, pattern = "a|b"), start = 2, end = -1))) |> 
    mutate(Region1 = case_when(Region1 == region_names[2] ~ regions[2],
                               Region1 == region_names[1] ~ regions[1],
                               Region1 == region_names[3] ~ regions[3],
                               Region1 == region_names[4] ~ regions[4]),
           Region2 = case_when(Region2 == region_names[2] ~ regions[2],
                               Region2 == region_names[1] ~ regions[1],
                               Region2 == region_names[3] ~ regions[3],
                               Region2 == region_names[4] ~ regions[4])) |> 
    left_join(teams, by = c("Team1" = "TeamID")) |> 
    left_join(teams, by = c("Team2" = "TeamID"), suffix = c("1", "2"))
  
  bracketDataFull <- bracketData |> 
    bind_rows(bracketData |> 
                rename_with(~ gsub("1", "A", .x, fixed = TRUE), ends_with("1")) |> 
                rename_with(~ gsub("2", "B", .x, fixed = TRUE), ends_with("2")) |> 
                rename_with(~ gsub("A", "2", .x, fixed = TRUE), ends_with("A")) |> 
                rename_with(~ gsub("B", "1", .x, fixed = TRUE), ends_with("B")) |> 
                dplyr::select(colnames(bracketData)))
  
  # First four play-in games
  firstFour <- bracketDataFull |> 
    dplyr::filter(PlayIn) |> 
    dplyr::mutate(Round = 0, 
                  Matchup = as.integer(factor(paste0(ifelse(Team1 < Team2, paste0(Team1, "_", Team2), 
                                                                       paste0(Team2, "_", Team1)))))) |> 
    dplyr::select(Seed1, Seed2, Region1, Region2, Round, Matchup)
  
  # Possible matchups
  round1 <- data.frame(Seed1 = 1:8, Seed2 = 16:9, 
                       Region1 = rep(c(regions[2], regions[4], regions[3], regions[1]), each = 8)) |> 
    dplyr::mutate(Region2 = Region1, Round = 1,
                  Matchup = case_when(Seed1 == 1 ~ 1,
                                      Seed1 == 8 ~ 2,
                                      Seed1 == 5 ~ 3,
                                      Seed1 == 4 ~ 4,
                                      Seed1 == 6 ~ 5,
                                      Seed1 == 3 ~ 6,
                                      Seed1 == 7 ~ 7,
                                      Seed1 == 2 ~ 8))
  
  round2 <- map_dfr(.x = rep(list(list(c(1, 16), c(8, 9)), list(c(5, 12), c(4, 13)), 
                                  list(c(6, 11), c(3, 14)), list(c(7, 10), c(2, 15))), 4), 
                    .f = function(x) {expand_grid(Seed1 = x[[1]], Seed2 = x[[2]])}) |>  
    mutate(Region1 = rep(c(regions[2], regions[4], regions[3], regions[1]), each = 16)) |> 
    mutate(Region2 = Region1, Round = 2,
           Matchup = case_when(Seed1 %in% c(1, 16) ~ 1,
                               Seed1 %in% c(5, 12) ~ 2,
                               Seed1 %in% c(6, 11) ~ 3,
                               Seed1 %in% c(7, 10) ~ 4))
  
  round3 <- expand_grid(Seed1 = c(1, 16, 8, 9), Seed2 = c(5, 12, 4, 13), 
                        Region1 = c(regions[2], regions[4], regions[3], regions[1])) |>
    bind_rows(expand_grid(Seed1 = c(6, 11, 3, 14), Seed2 = c(7, 10, 2, 15), 
                          Region1 = c(regions[2], regions[4], regions[3], regions[1]))) |> 
    dplyr::mutate(Region2 = Region1, Round = 3, Matchup = rep(1:2, each = 64))
  
  round4 <- expand_grid(Seed1 = c(1, 16, 8, 9, 5, 12, 4, 13), 
                        Seed2 = c(6, 11, 3, 14, 7, 10, 2, 15), 
                        Region1 = c(regions[2], regions[4], regions[3], regions[1])) |> 
    dplyr::mutate(Region2 = Region1, Round = 4, Matchup = 1)
  
  round5 <- expand_grid(Seed1 = 1:16, Seed2 = 1:16, 
                        Region1 = c(regions[1], regions[3])) |> 
    dplyr::mutate(Region2 = ifelse(Region1 == regions[1], regions[2], regions[4]), Round = 5, 
                  Matchup = 1)
  
  round6 <- expand_grid(Seed1 = 1:16, Seed2 = 1:16, 
                        Region1 = c(regions[1], regions[2]),
                        Region2 = c(regions[3], regions[4])) |> 
    dplyr::mutate(Round = 6, Matchup = 1)
  
  roundsWide <- bind_rows(firstFour, round1, round2, round3, 
                          round4, round5, round6) |> 
    left_join(bracketDataFull |> 
                dplyr::select(-Season, -Team1, -Team2),
              relationship = "many-to-many")
  
  roundsLong <- roundsWide |> 
    pivot_longer(cols = c(Seed1, Seed2), 
                 names_to = "Team", values_to = "Seed") |> 
    arrange(Round, Region1, Matchup, Team, Seed) |> 
    dplyr::select(-Team, -Pred2)
  
  return(roundsLong)
}

# Function for walking through tournament given winners
walk_tournament <- function(rounds_data) {
  
  # Winners from first four play-in games
  r0Winners <- pull(dplyr::ungroup(dplyr::slice(dplyr::group_by(dplyr::filter(rounds_data, Round == 0), Matchup), 1)), Winner)
  
  playins <- unlist(dplyr::select(dplyr::ungroup(dplyr::slice(dplyr::group_by(dplyr::filter(rounds_data, Round == 0), Matchup), 1)), TeamName1:TeamName2))
  
  r0Losers <- playins[which(!(playins %in% r0Winners))]
  
  # Winners from round 1: Round of 32
  r1Res <- dplyr::filter(rounds_data, Round == 1, !(TeamName1 %in% r0Losers), 
                              !(TeamName2 %in% r0Losers))
  r1Winners <- r1Res$Winner
  r1Losers <- r1Res$Loser
  
  # Winners from round 2: Sweet Sixteen
  r2Winners <- dplyr::filter(rounds_data, Round == 2, TeamName1 %in% r1Winners, 
                              TeamName2 %in% r1Winners)$Winner
  
  # Winners from round 3: Elite Eight
  r3Winners <- dplyr::filter(rounds_data, Round == 3, TeamName1 %in% r2Winners, 
                              TeamName2 %in% r2Winners)$Winner
  
  # Winners from round 4: Final Four
  r4Winners <- dplyr::filter(rounds_data, Round == 4, TeamName1 %in% r3Winners, 
                              TeamName2 %in% r3Winners)$Winner
  
  # Winners from round 5: Championship
  r5Winners <- dplyr::filter(rounds_data, Round == 5, TeamName1 %in% r4Winners, 
                              TeamName2 %in% r4Winners)$Winner
  
  # Winners from round 6: Grand overall winner
  r6Winners <- dplyr::filter(rounds_data, Round == 6, TeamName1 %in% r5Winners, 
                              TeamName2 %in% r5Winners)$Winner
  
  return(c(r1Losers, r1Winners,
           r1Winners, 
           r2Winners,
           r3Winners, 
           r4Winners,
           r5Winners,
           r6Winners))
}
```

```{r}
library(tidyverse)
library(furrr)

winners_datas <- map(.x = womens, .f = function(x) {
  dplyr::mutate(make_matchups_data(seeds = mySeeds[[ifelse(x, "W", "M")]],
                                 submission = lda_submissions[[ifelse(x, "W", "M")]],
                                 teams = myTeams[[ifelse(x, "W", "M")]],
                                 regions = region_info[[ifelse(x, "W", "M")]]) |> 
                  dplyr::distinct() |> 
                  mutate(game_id = as.integer(as.factor(ifelse(TeamName1 < TeamName2, 
                                                               str_c(TeamName1, "_", TeamName2),
                                                               str_c(TeamName2, "_", TeamName1))))) |> 
                  group_by(game_id) |> 
                  slice_head(n = 1) |> 
                  ungroup() |> 
                  dplyr::select(-game_id), 
                                          Winner = ifelse(Pred1 > 0.5, TeamName1, TeamName2),
                                          Loser = ifelse(Pred1 <= 0.5, TeamName1, TeamName2))})

for(women in c(TRUE, FALSE)) {
tourney_year <- 2024
model <- "Awin"

# Setting working directory
setwd(paste0(start_dir, tourney_year))

# Setting file paths
stageDir <- paste0("march-machine-learning-mania-", tourney_year, "/")

# Importing model predictions
pred_submission <- lda_submissions[[ifelse(women, "W", "M")]]

teamsPath <- paste0(stageDir, ifelse(women, "W", "M"), "Teams.csv")

# Prediction data on matchups
long_rounds <- make_matchups_data(seeds = mySeeds[[ifelse(women, "W", "M")]],
                                         submission = lda_submissions[[ifelse(women, "W", "M")]],
                                         teams = myTeams[[ifelse(women, "W", "M")]],
                                         regions = region_info[[ifelse(women, "W", "M")]]) |> 
  dplyr::distinct() |> 
  mutate(game_id = as.integer(as.factor(ifelse(TeamName1 < TeamName2, 
                          str_c(TeamName1, "_", TeamName2),
                          str_c(TeamName2, "_", TeamName1))))) |> 
  group_by(game_id) |> 
  slice_head(n = 1) |> 
  ungroup() |> 
  dplyr::select(-game_id)

# Rounds to matchup with teams for each simulation from walk_tournament()
rounds <- rep(c("First Round", "Round of 32", "Sweet 16", "Elite 8", 
                "Final 4", "Final", "Champion"), 
              times = c(64, 32, 16, 8, 4, 2, 1))

# Generating values from uniform(0, 1) to help simulate game outcomes
winners_data <- dplyr::mutate(long_rounds, 
                              Winner = ifelse(Pred1 > 0.5, TeamName1, TeamName2),
                              Loser = ifelse(Pred1 <= 0.5, TeamName1, TeamName2))

# Deterministic walk through tournament
tourney_results <- walk_tournament(rounds_data = winners_data)

# Generating values from uniform distribution for simulations
n_games <- nrow(long_rounds)
n_sims <- 100000
set.seed(1994)

# Test code for timing things
# timing_res <- bench::mark({coin_flips <- long_rounds$Pred1 > runif(n = n_games, min = 0, max = 1)
#                           walk_tournament(rounds_data = dplyr::mutate(long_rounds,
#                           Winner = ifelse(coin_flips, TeamName1, TeamName2),
#                           Loser = ifelse(!coin_flips, TeamName1, TeamName2)))})


if(file.exists(paste0("sim_results_", tourney_year, "_", ifelse(women, "W", "M"), "_", model, "_N", n_sims, ".rds")) == FALSE) {
# Set a "plan" for how the code should run.
plan(multisession, workers = 4)
t1 <- Sys.time()

  # Simulating walks through tournament
sim_results <- tibble(Team = unlist(furrr::future_map(.x = 1:n_sims,
        .f = function(sim_num) {
          coin_flips <- long_rounds$Pred1 > runif(n = n_games, min = 0, max = 1)
          return(walk_tournament(rounds_data = dplyr::mutate(long_rounds,
                                            Winner = ifelse(coin_flips, TeamName1, TeamName2),
                                            Loser = ifelse(!coin_flips, TeamName1, TeamName2))))
        }, .progress = TRUE)), Round = rep(rounds, times = n_sims))

# Saving simulations results
write_rds(sim_results, file = paste0("sim_results_", tourney_year, "_", ifelse(women, "W", "M"), "_", model, "_N", n_sims, ".rds"))

}

if(file.exists(paste0("sim_summary_", tourney_year, "_", ifelse(women, "W", "M"), "_", model, "_N", n_sims, ".rds")) == FALSE) {
  # Import simulation results from saved file
  sim_results <- read_rds(paste0("sim_results_", tourney_year, "_", ifelse(women, "W", "M"), "_", model, "_N", n_sims, ".rds"))
  
# Summarizing simulations with probability of reaching each round
sim_summary <- sim_results |> 
  janitor::tabyl(Team, Round, show_missing_levels = TRUE) |> 
  dplyr::select(c("Team", "First Round", "Round of 32", "Sweet 16", "Elite 8", 
                "Final 4", "Final", "Champion")) |> 
  mutate(across(where(is.double), ~ .x / n_sims))

# Most like sets of teams in rounds
rounds_summary <- sim_results |> 
  mutate(sim = rep(1:n_sims, each = length(rounds))) |> 
  group_by(sim, Round) |> 
  summarize(Teams = paste(sort(Team), collapse = ", ")) |> 
  ungroup() |> 
  count(Round, Teams) |> 
  group_by(Round) |> 
  slice_max(n, n = 10) |> 
  dplyr::filter(n > 1) |> 
  mutate(prop = n / n_sims)

# Saving simulation summary results
write_rds(list(sim_summary = sim_summary,
               rounds_summary = rounds_summary), 
          file = paste0("sim_summary_", tourney_year, "_", ifelse(women, "W", "M"), "_", model, "_N", n_sims, ".rds"))
}

}

# Function for labelling percents
percent_labeller <- scales::label_percent(accuracy = 0.01, scale = 100)

# Check duplicates rows in long_rounds: is this encoded correctly?

### Ideas for improving speed of code
### a) Encode team names (TeamName1 and TeamName2) as factors
### b) Encode regions (Region1 and Region2) as factors
### b) Drop the Pred1, PlayIn, and Seed variables
```

Tournament Brackets
===================================== 

Row {.tabset .tabset-fade data-height=700}
-----------------------------------------------------------------------

### Mens

```{r, fig.width = 25, fig.height= 7}
# Function to adjust alignment of text for different geom_text() layers
text_adjust_plotly <- function(my_plotly, layers = 1, adjustment = "right") {
  for(layer in layers) {
    my_plotly[["x"]][["data"]][[layer]][["textposition"]] <- adjustment
  }
  
  return(my_plotly)
}

### Layers 2 - 8
## (2) regions 1 and 2 games
## (3) regions 3 and 4 games
## (4) play-in games
## (5) championship game
## (6) champion
## (7) region labels for regions 1 & 2
## (8) region labels for regions 3 & 4
plotly::ggplotly(bracket_res_mens$bracketGG, tooltip = "text") |> 
  plotly::style(textposition = "right") |> 
  text_adjust_plotly(layers = c(2, 4, 5, 7), adjustment = "right") |> 
  text_adjust_plotly(layers = c(3, 8), adjustment = "left") |> 
  text_adjust_plotly(layers = 6, adjustment = "center") |> 
  layout(autosize = TRUE)
```

### Womens

```{r, fig.width = 25, fig.height= 7}
plotly::ggplotly(bracket_res_womens$bracketGG, tooltip = "text") |> 
  plotly::style(textposition = "right") |> 
  text_adjust_plotly(layers = c(2, 4, 5, 7), adjustment = "right") |> 
  text_adjust_plotly(layers = c(3, 8), adjustment = "left") |> 
  text_adjust_plotly(layers = 6, adjustment = "center")
```

Team Ratings & Round Probabilities
===================================== 

Row {.tabset .tabset-fade data-height=700}
-----------------------------------------------------------------------

### Mens

```{r}
# Function to calculate power rankings for teams
power_rankings <- function(myData, bracket_res) {
  myData <- bind_rows(myData |> 
  dplyr::mutate(Team = Favorite, 
                Prob = `Favorite Win Probability`) |> 
  dplyr::select(Team, Prob),
 bracket_res$ret |> 
  dplyr::mutate(Team = Underdog, 
                Prob = 1 - `Favorite Win Probability`) |> 
  dplyr::select(Team, Prob)) |> 
  dplyr::group_by(Team) |> 
  dplyr::summarize(Rating = sum(Prob)) |> 
  dplyr::ungroup() |> 
  dplyr::mutate(Rank = rank(-Rating), 
                Rating = as.numeric(scale(Rating, center = TRUE, scale = TRUE))) |> 
  dplyr::arrange(Rank) |> 
  dplyr::select(Rank, Team, Rating)
  
  return(myData)
}

# Function for creating table of team power rankings
rank_table <- function(myData, gradColors = color_gradient, bracket_res) {
  myData <- power_rankings(myData, bracket_res = bracket_res) 
  
  myData |> 
  reactable(showSortIcon = FALSE,
          searchable = TRUE,
          filterable = TRUE,
          language = reactableLang(
            searchPlaceholder = "Search for a team...",
            pageInfo = "{rowStart}\u2013{rowEnd} of {rows} teams",
            noData = "That team does not exist."),
            defaultColDef = colDef(
              maxWidth = 65,
              style = color_scales(myData, colors = gradColors),
              filterable = FALSE
            ),
          columns = list(
              Rank = colDef(
              maxWidth = 65,
              style = color_scales(myData, colors = gradColors),
              filterable = TRUE
            ),
              Team = colDef(maxWidth = 300, filterable = TRUE, rowHeader = TRUE, sticky = "left"),
            Rating = colDef(
              filterable = FALSE,
              maxWidth = 300,
              align = "center",
              cell = data_bars(
                myData,
                fill_color = rev(gradColors),
                number_fmt = scales::label_number(accuracy = 0.01)
              ),
              style = list(borderLeft = "1px solid rgba(0, 0, 0, 0.3)")
            )
          ),
defaultPageSize = 40) |> 
  add_title(title = "Team ratings are standardized win probabilities summed across all possible matchups of all NCAA teams.", font_size = 10) |> 
  google_font(font_family = str_to_title(fontFamily))
}

# Function for making data for round / power rankings table
round_power_data <- function(summary_data, bracket_data, region_data, bracket_res) {
  # Adding seed and region information
round_probs <- summary_data |> left_join(bind_rows(dplyr::rename(dplyr::distinct(bracket_data, SeedFav, Favorite), "Team" = "Favorite", "Seed" = "SeedFav"),                                              dplyr::rename(dplyr::distinct(bracket_data, SeedDog, Underdog), "Team" = "Underdog", "Seed" = "SeedDog")) |>
  dplyr::distinct() |> 
  drop_na()) |> 
  left_join(bind_rows(dplyr::rename(dplyr::distinct(region_data, TeamName1, Region1), "Region" = "Region1", "Team" = "TeamName1"),                                              dplyr::rename(dplyr::distinct(region_data, TeamName2, Region2), "Region" = "Region2", "Team" = "TeamName2")) |>
    dplyr::distinct() |> 
    drop_na())

# Adding in power rankings and displaying table
round_power <- round_probs |> 
  left_join(power_rankings(myData = bracket_data, bracket_res = bracket_res)) |> 
  dplyr::select(Region, Seed, Rank, Team, Rating, everything())

return(round_power)
}

# Function for creating reactable table
# Following example at: https://kcuilla.github.io/reactablefmtr/articles/themes.html
round_reactable_fun <- function(myData, logo_info = team_logos, gradColors = color_gradient, ndigits = 1) {
 myData |> 
    dplyr::mutate(merge_team = str_remove_all(str_to_lower(Team), pattern = " ")) |> 
    left_join(logo_info,
              by = c("merge_team" = "merge_team")) |> 
    dplyr::distinct(Team, .keep_all = TRUE) |> 
   dplyr::select(Region:Rank, path, everything(), -merge_team, -TeamID) |>  
  reactable(showSortIcon = FALSE,
          searchable = TRUE,
          defaultSorted = list(Rank = "asc"),
          language = reactableLang(
            searchPlaceholder = "Search in table...",
            pageInfo = "{rowStart}\u2013{rowEnd} of {rows} teams",
            noData = "That team does not exist."),
            defaultColDef = colDef(
    maxWidth = 100,
    format = colFormat(percent = TRUE, digits = ndigits),
    style = color_scales(myData, colors = rev(gradColors))
),
          columns = list(
              Region = colDef(maxWidth = 100),
              Seed = colDef(
                rowHeader = TRUE, sticky = "left",
              maxWidth = 60,
              format = colFormat(digits = 0),
                  style = color_scales(myData, colors = gradColors)
            ),
              Rank = colDef(
                name = "Power Rank",
              maxWidth = 85,
              format = colFormat(digits = 0),
                  style = color_scales(myData, colors = gradColors)
            ),
                  path = colDef(cell = function(value) {
    img_src <- knitr::image_uri(value)
    image <- htmltools::img(src = img_src, style = "height: 24px;")
    htmltools::tagList(
        htmltools::div(style = "display: inline-block; width: 45px", image)
    )
},     format = NULL,
    style = NULL, maxWidth = 100,  align = "center", name = "", sticky = "left", sortable = FALSE),
              Team = colDef(maxWidth = 150, rowHeader = TRUE, sticky = "left"),
              Rating = colDef(
              filterable = FALSE,
                name = "Power Rating",
              maxWidth = 100,
              align = "center",
              cell = data_bars(
                myData,
                fill_color = rev(gradColors),
                number_fmt = scales::label_number(accuracy = 0.01)
              ),
              style = list(borderLeft = "1px solid rgba(0, 0, 0, 0.3)")
            )
          ),
defaultPageSize = 40) |> 
  add_title(title = "Model data source: Kaggle", font_size = 10) |> 
  google_font(font_family = str_to_title(fontFamily))
}
```

```{r}
# Importing simulation summary data
  sim_summary_lists_awin <- map(.x = womens,
                                .f = function(x) {
                                  read_rds(paste0("sim_summary_", tourney_year, "_", ifelse(x, "W", "M"), "_", "Awin", "_N", n_sims, ".rds"))
                                })

# Displaying reactable table
round_power_data(summary_data = sim_summary_lists_awin$M$sim_summary,
                 bracket_data = bracket_res_mens$ret,
                 region_data = winners_datas$M,
                 bracket_res = bracket_res_mens) |> 
  round_reactable_fun()
```

### Womens

```{r}
# Displaying reactable table
round_power_data(summary_data = sim_summary_lists_awin$W$sim_summary,
                 bracket_data = bracket_res_womens$ret,
                 region_data = winners_datas$W,
                 bracket_res = bracket_res_womens) |> 
  round_reactable_fun()
```

Matchup Probabilities
===================================== 

Row {.tabset .tabset-fade data-height=700}
-----------------------------------------------------------------------

### Mens

```{r, include = FALSE, eval = TRUE}
# Function for creating reactable table
# Following example at: https://kcuilla.github.io/reactablefmtr/articles/themes.html
matchups_table <- function(myData, gradColors = color_gradient) {
  myData |> 
    drop_na() |> 
  reactable(showSortIcon = FALSE,
          searchable = TRUE,
          filterable = TRUE,
          language = reactableLang(
            searchPlaceholder = "Search for a matchup...",
            pageInfo = "{rowStart}\u2013{rowEnd} of {rows} matchups",
            noData = "That matchup does not exist."),
            defaultColDef = colDef(
              maxWidth = 65,
              style = color_scales(myData, colors = gradColors),
              filterable = FALSE
            ),
          columns = list(
              SeedFav = colDef(
                name = "Seed",
              maxWidth = 65,
              style = color_scales(myData, colors = gradColors),
              filterable = TRUE
            ),
              Favorite = colDef(maxWidth = 300, filterable = TRUE, rowHeader = TRUE, sticky = "left"),
              SeedDog = colDef(
                name = "Seed",
              maxWidth = 65,
              style = color_scales(myData, colors = gradColors),
              filterable = TRUE
            ),
              Underdog = colDef(maxWidth = 300, filterable = TRUE, rowHeader = TRUE, sticky = "left"),
            `Favorite Win Probability` = colDef(
              name = "Favorite Win Probability",
              filterable = FALSE,
              maxWidth = 300,
              align = "center",
              cell = data_bars(
                myData,
                fill_color = rev(gradColors),
                number_fmt = scales::label_percent(accuracy = 0.1)
              ),
              style = list(borderLeft = "1px solid rgba(0, 0, 0, 0.3)")
            )
          ),
defaultPageSize = 40) |> 
  add_title(title = "Model data source: Kaggle", font_size = 10) |> 
  google_font(font_family = str_to_title(fontFamily))
}
```

```{r, eval = TRUE, include = TRUE}
setwd(paste0(start_dir, tourney_year))

# Following example at: https://kcuilla.github.io/reactablefmtr/articles/themes.html
matchups_table(myData = bracket_res_mens$ret)
```

### Womens

```{r, eval = TRUE, include = TRUE}
setwd(paste0(start_dir, tourney_year))

# Following example at: https://kcuilla.github.io/reactablefmtr/articles/themes.html
matchups_table(myData = bracket_res_womens$ret)
```
